---
title: 'OHI 2021: Seagrass health'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../workflow/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---


```{r setup, include=FALSE}

library(readr)      # for read_csv()
library(raster)
library(here)
library(sf)
library(fasterize)
library(tidyverse)
library(broom)
library(mapview)
library(ggplot2)

source('http://ohi-science.org/ohiprep_v2021/workflow/R/common.R')

goal     <- 'globalprep/hab_seagrass/v2021'
dir_git  <- file.path('~/github/ohiprep_v2021', goal)
dir_waycott <- file.path(dir_git, "waycott_data_extract")
ohi_rasters()
regions_shape()

```

## Methods

 - Apply a global health value to all regions. 
 
 Taken from [Waycott et al. 2009](https://www.pnas.org/content/106/30/12377):
  - Our comprehensive global assessment of 215 studies found that seagrasses have been disappearing at a rate of 110 km2 yr−1 since 1980 and that 29% of the known areal extent has disappeared since seagrass areas were initially recorded in 1879.
  
Based on this, we will score all regions health as 1 - 0.29 = 0.71. 


```{r}
seagrass_extent <- read_csv("data/habitat_extent_seagrass_updated.csv")  ## read in extent data

## give all regions a health score of 0.71

seagrass_health <- seagrass_extent %>%
  dplyr::select(-km2) %>%
  mutate(health = 0.71) %>%
  mutate(year = 2021)

write.csv(seagrass_health, "data/habitat_health_seagrass_updated.csv", row.names = FALSE)

seagrass_health_gf <- seagrass_health %>%
  mutate(gap_fill = "global value") %>%
  dplyr::select(-health)

write.csv(seagrass_health_gf, "data/health_seagrass_gf.csv", row.names = FALSE)

```

