---
title: 'OHI 2021: saltmarsh condition'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../workflow/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

# Summary

https://cdnsciencepub.com/doi/10.1139/anc-2017-0001

This script generates the condition of saltmarsh. Use this "25% decline estimate" meaning that the condition is 0.75 for each region. 



## Updates from previous assessment

***
## Data Source 

Li, X., Bellerby, R., Craft, C., Widney, S.E., 2018. Coastal wetland loss, consequences, and challenges for restoration. Anthropocene Coasts 1–15. https://doi.org/10.1139/anc-2017-0001


**Downloaded**: October 5, 2021

**Description**:  

**Time range**: 


***
# Methods



## Setup
``` {r setup, echo = FALSE, message = FALSE, warning = FALSE}
library(readr)      # for read_csv()
library(raster)
library(here)
library(sf)
library(fasterize)
library(tidyverse)
library(mapview)
library(sp)
library(rgeos)
library(janitor)


source(file.path('~/github/ohiprep_v2021/workflow/R/common.R'))

goal     <- 'globalprep/hab_saltmarsh/v2021'
dir_git  <- file.path('~/github/ohiprep_v2021', goal)
region_data()

dir_git_old  <- file.path('~/github/ohiprep_v2021', "globalprep/hab_saltmarsh/v2012")



```

```{r}
## read in extent data
all <- read.csv(file.path(here("globalprep/hab_saltmarsh/v2021/data/habitat_extent_saltmarsh_updated.csv")))

# specify trend
all <- all %>%
  filter(km2 > 0) %>%
  filter(rgn_id < 255) %>%
  dplyr::select(-year) %>%
  mutate(health = 0.75)


# Save gapfilling 

health_gaps <- all %>%
  mutate(variable = "health") %>%
  mutate(habitat = "saltmarsh") %>%
  mutate(gapfill = 1) %>% 
  dplyr::select(-km2)
write.csv(health_gaps, here('globalprep/hab_saltmarsh/v2021/data/health_saltmarsh_gf.csv'), row.names=FALSE)

### save trend data:
health <- trend_gaps %>%
  dplyr::select(rgn_id, habitat, health) %>%
  mutate(year = 2021)
write.csv(health, here('globalprep/hab_saltmarsh/v2021/data/habitat_health_saltmarsh_updated.csv'), row.names=FALSE)
```










