---
title: "Untitled"
author: "Gage Clawson"
date: "8/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rfishbase)
library(parallel)
library(dplyr)
library(here)
```

```{r}
## fishbase 
sp <- read.csv("fb_sp_stks.csv")$x

fb <- validate_names(sp)

# fb <- read.csv("fb_stks.csv")$x

fb_list <- list()

for(i in 1:length(fb)){
   # i = 2
  resil <- list(rfishbase::stocks(fb[i], fields = c("Resilience", "Species", "SpecCode")))
  
  fb_list <- c(fb_list, resil)
}


res <- do.call(rbind.data.frame, fb_list) %>% 
  distinct() 

res <- res %>%
  rename(sciname = Species)

write.csv(res, "res_local.csv", row.names = FALSE)

## sealifebase

sp_w_nas <- read.csv("sp_w_nas.csv")$x

fb_list <- list()

for(i in 26:length(sp_w_nas)){
   # i = 2
  resil <- list(rfishbase::stocks(sp_w_nas[i], fields = c("Resilience", "Species", "SpecCode"), server = "sealifebase"))
  
  fb_list <- c(fb_list, resil)
  
  print(sp_w_nas[i])
}


res <- do.call(rbind.data.frame, fb_list)%>%
        distinct()

write.csv(res, "res_nas_local.csv", row.names = FALSE)

```

