---
title: "sb_extent_explore"
output: html_document
date: '2022-08-31'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(terra)
library(tidyverse)
library(raster)
```

```{r}
sb_hab_raw <- rast("/home/jcohen/s_t_s_bottom_lzw.tif")
sb_hab_raw
# 934 x 934 meters, Mollweide
```

```{r}
fish_effort <- rast("/home/shares/ohi/git-annex/globalprep/hab_prs_hd_subtidal_soft_bottom/v2022/final_rasters/dredging_trawling_combined_2020.tif")
fish_effort
# 0.01 degree, 4326

# fish_effort[is.na(fish_effort)] <- 0

plot(cellSize(fish_effort, unit = "km"))
```

Project the soft bottom habitat (in meters, Mollweide) to coarser resolution of fishing effort raster (degrees, 4326).

```{r}


sb_hab_coarse <- terra::aggregate(x = sb_hab_raw, fact = 5, fun = "sum", na.rm = TRUE) 
sb_hab_coarse
# 4672.394 x 4672.394 meters


sb_hab_prop <- sb_hab_coarse/25

fish_effort_coarse <- terra::aggregate(x = fish_effort, fact = 5, fun = "sum", na.rm = TRUE)
global(fish_effort, "sum", na.rm = TRUE)
global(fish_effort_coarse, "sum", na.rm = TRUE) # 18379444

fish_effort_hr_km <- fish_effort_coarse/cellSize(fish_effort_coarse, unit = "km")

fish_effort_reproj <- project(fish_effort_hr_km, sb_hab_prop)

fish_effort_reproj_fix <- fish_effort_reproj*21.83127

global(fish_effort_reproj_fix, "sum", na.rm = TRUE) # 18541882


multiply <- fish_effort_reproj_fix*sb_hab_prop
multiply[is.na(multiply)] = 0 

sb_hab_coarse_fix <- sb_hab_coarse
sb_hab_coarse_fix[sb_hab_coarse >= 1] <- 1

multiply_mask <- mask(multiply, mask = sb_hab_coarse_fix)

# multiply_mask[multiply_mask == 0] <- 10000000000 # test


plot(log(multiply_mask+1))
plot(multiply_mask)
zoom(multiply_mask)
click(multiply_mask)

## convert sb_hab_coarse to >=1 = 1 
## mask by converted sb_hab_coarse to keep healthy SB habitats 
## rescale these rasters by 99.9 or something (0-1); THIS IS THE PRESSURE
## then extract by OHI region 
##TO GET HEALTH: 1 - PRESSURE from above step

```

















Change crs to mollewide 

```{r}
#mollCRS <- CRS("+proj=moll")
#fish_effort_mol <- terra::project(fish_effort, mollCRS)
```

Make extents match

```{r}
#compareGeom(sb_hab_raw, fish_effort)

#ext(sb_hab_raw)
#ext(fish_effort)

```

```{r}
#fish_effort_extended <- terra::extend(fish_effort, sb_hab_raw)
#ext(fish_effort_extended)

#sb_raw_extended
```

